ObslugaKursow/ObslugaKursow/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.EntityFramework;
using ObslugaKursow.Models;

namespace ObslugaKursow.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class RolesController : Controller
    {
        ApplicationDbContext context;

        public RolesController()
        {
           context = new ApplicationDbContext();
        }
        // GET: Roles
        /// <summary>
        /// Get All Roles
        /// </summary>
        /// <returns>List of all aplication roles.</returns>
        public ActionResult Index()
        {
            
            var roles = context.Roles.ToList();
            return View(roles);
        }

        public ActionResult Create()
        {
            var role = new IdentityRole();
            return View(role);
        }

        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ObslugaKursow/ObslugaKursow/Views/Roles/AssignRoleToUser.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "AssignRoleToUser";
}

<h2>AssignRoleToUser</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.Label("Wybierz typ użytkownika", new { @class = "col-md-2 control-label" })
        <div class="col-lg-10">
            @Html.DropDownList("UserName")
        </div>
    </div>
}

ObslugaKursow/ObslugaKursow/Views/Roles/Create.cshtml
@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@{
    ViewBag.Title = "title";
}

<h2>Dodaj nową rolę</h2>



@using (Html.BeginForm())
{
    <table class="table table-bordered table-hover">
        <tr>
            <td>Nazwa roli:</td>
            <td>
                @Html.EditorFor(m=>m.Name)
            </td>
        </tr>
    </table>
    <input type="submit" value="Dodaj"/>
}

ObslugaKursow/ObslugaKursow/Views/Roles/Index.cshtml
@model System.Collections.Generic.List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>

@{
    ViewBag.Title = "title";
}
@*<style type="text/css">
    #tbrole, .c {
        border: double;
    }
</style>*@
<h2>Role dla Aplikacji</h2>

<section class="col-sm-6">
    <table class="table-bordered">
        @Html.ActionLink("Utwórz nową", "Create", "Roles")
    </table>
</section>

<section class="col-sm-6">
    <table class="table-bordered">
        @Html.ActionLink("Przypisz role użytkownikowi", "RegisterRole", "Account")
    </table>
</section>

<table class="c">
    <tr>
        <th class="c">
            Nazwa roli
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td class="c">
                @item.Name
            </td>
        </tr>
    }

</table>