ObslugaKursow/ObslugaKursow/Models/EdycjaKursu.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObslugaKursow.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdycjaKursu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EdycjaKursu()
        {
            this.Spotkania = new HashSet<Spotkanie>();
            this.Uczestnictwa = new HashSet<Uczestnictwo>();
        }
    
        public int IdEdycji { get; set; }
        public string NazwaEdycji { get; set; }
        public string WarunekUczestnictwa { get; set; }
        public int idKursu { get; set; }
    
        public virtual Kurs Kurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spotkanie> Spotkania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uczestnictwo> Uczestnictwa { get; set; }
    }
}

ObslugaKursow/ObslugaKursow/Controllers/EdycjaKursuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ObslugaKursow.Models;

namespace ObslugaKursow.Controllers
{
    [Authorize]
    public class EdycjaKursuController : Controller
    {
        private KursyDB db = new KursyDB();

        // GET: EdycjaKursu
        //[Authorize]
        public ActionResult Index()
        {
            var edycjeKursu = db.EdycjeKursu.Include(e => e.Kurs).Include(e=>e.Spotkania);
            return View(edycjeKursu.ToList());
        }

        // GET: EdycjaKursu/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EdycjaKursu edycjaKursu = db.EdycjeKursu.Find(id);
            if (edycjaKursu == null)
            {
                return HttpNotFound();
            }
            return View(edycjaKursu);
        }

        // GET: EdycjaKursu/Create
        public ActionResult Create()
        {
            ViewBag.idKursu = new SelectList(db.Kursy, "IdKursu", "Nazwa");
            return View();
        }

        // POST: EdycjaKursu/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdEdycji,NazwaEdycji,WarunekUczestnictwa,idKursu")] EdycjaKursu edycjaKursu)
        {
            if (ModelState.IsValid)
            {
                db.EdycjeKursu.Add(edycjaKursu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idKursu = new SelectList(db.Kursy, "IdKursu", "Nazwa", edycjaKursu.idKursu);
            return View(edycjaKursu);
        }

        // GET: EdycjaKursu/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EdycjaKursu edycjaKursu = db.EdycjeKursu.Find(id);
            if (edycjaKursu == null)
            {
                return HttpNotFound();
            }
            ViewBag.idKursu = new SelectList(db.Kursy, "IdKursu", "Nazwa", edycjaKursu.idKursu);
            return View(edycjaKursu);
        }

        // POST: EdycjaKursu/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdEdycji,NazwaEdycji,WarunekUczestnictwa,idKursu")] EdycjaKursu edycjaKursu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(edycjaKursu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idKursu = new SelectList(db.Kursy, "IdKursu", "Nazwa", edycjaKursu.idKursu);
            return View(edycjaKursu);
        }

        // GET: EdycjaKursu/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EdycjaKursu edycjaKursu = db.EdycjeKursu.Find(id);
            if (edycjaKursu == null)
            {
                return HttpNotFound();
            }
            return View(edycjaKursu);
        }

        // POST: EdycjaKursu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EdycjaKursu edycjaKursu = db.EdycjeKursu.Find(id);
            db.EdycjeKursu.Remove(edycjaKursu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Contribute(int idEdycji)
        {
            EdycjaKursu edycja = db.EdycjeKursu.FirstOrDefault(x => x.IdEdycji == idEdycji);
            edycja.Kurs = db.Kursy.FirstOrDefault(x => x.IdKursu == edycja.idKursu);
            return View(edycja);
        }
        [HttpPost]
        public ActionResult NowaKategoria(string Nazwa)
        {
            if (Nazwa != "" || !db.Kursy.Any(x => x.Nazwa.Equals(Nazwa)))
            {
                db.Kategorie.Add(new Kategoria { Nazwa = Nazwa });
                db.SaveChanges();
                var x = db.Kategorie.ToList();
            }

            return View(Nazwa);
        }
    }
}

ObslugaKursow/ObslugaKursow/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ObslugaKursow.Models;

namespace ObslugaKursow.Controllers
{

    public class TestController : Controller
    {
        // private KursyDB db = new KursyDB();
        //   private TestContext db = new Test1Context();
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Uczestnicz(List<HttpPostedFileBase> files, int IdEdycji)
        {
            string UserID = System.Web.HttpContext.Current.User.Identity.GetUserId();
            KursyDB db = new KursyDB();
            Uczestnik uczestnik = db.Uczestnicy.FirstOrDefault(x =>
                x.AspNetUserId.Equals(UserID));
            
            bool uczestniczy = db.Uczestnictwa.Where(x => x.IdUczestnika == uczestnik.IdUczestnika)
                .Where(x => x.idEdycjiKursu == IdEdycji).Any();
            if (!uczestniczy)
            {
                Uczestnictwo noweUczestnictwo = new Uczestnictwo();
                noweUczestnictwo.DataZgloszenia = DateTime.Now;
                noweUczestnictwo.IdUczestnika = uczestnik.IdUczestnika;
                noweUczestnictwo.DataZgloszenia = DateTime.Now;
                noweUczestnictwo.idEdycjiKursu = IdEdycji;
                noweUczestnictwo.Potwierdzone = false;
                db.Uczestnictwa.Add(noweUczestnictwo);
                db.SaveChanges();
                var path = "";
                foreach (var file in files)
                {
                    if (file != null)
                    {
                        if (file.ContentLength > 0)
                        {
                            if (Path.GetExtension(file.FileName).ToLower() == ".jpg" ||
                                Path.GetExtension(file.FileName).ToLower() == ".jpeg" ||
                                Path.GetExtension(file.FileName).ToLower() == ".png")
                            {
                                Dokument nowyDokument = new Dokument();
                                nowyDokument.DataWczytania = DateTime.Now;
                                nowyDokument.idUczestnictwa = noweUczestnictwo.IdUczestnictwa;
                                nowyDokument.NazwaPliku = "";
                                db.Dokumenty.Add(nowyDokument);
                                db.SaveChanges();
                                path = Path.Combine(Server.MapPath("~/Content/Images"),
                                    nowyDokument.IdDokumentu.ToString() + Path.GetExtension(file.FileName).ToLower());
                                file.SaveAs((path));
                                ViewBag.UploadSuccess = true;
                                db.Dokumenty.FirstOrDefault(x => x.IdDokumentu == nowyDokument.IdDokumentu).NazwaPliku =
                                    nowyDokument.IdDokumentu.ToString() + Path.GetExtension(file.FileName).ToLower();
                                db.SaveChanges();
                            }
                        }
                    }
                }
            }

            return View();
        }
        [AllowAnonymous]
        public JsonResult getProductCategories()
        {
            KursyDB db = new KursyDB();
            List<Kategoria> kategorie = new List<Kategoria>();
            foreach (var dbKategoria in db.Kategorie)
            {
                if (dbKategoria.Nazwa != "")
                {
                    kategorie.Add(
                        new Kategoria() { Nazwa = dbKategoria.Nazwa, IdKategorii = dbKategoria.IdKategorii });
                }
            }

            //categories.Add(new Kategoria() { Nazwa = "kat1", IdKategorii = 1 });
            //categories.Add(new Kategoria() { Nazwa = "kat2", IdKategorii = 2 });
            return new JsonResult { Data = kategorie, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        [AllowAnonymous]
        public JsonResult GetKursyKategorii(Kategoria item)
        {
            KursyDB db = new KursyDB();
            List<Kurs> kursy = new List<Kurs>();
            foreach (var dbkurs in db.Kursy.Include(nameof(Kategoria)).Where(x => x.idKategorii == item.IdKategorii))
            {
                if (dbkurs.Nazwa != "")
                {
                    kursy.Add(
                        new Kurs() { Nazwa = dbkurs.Nazwa, IdKursu = dbkurs.IdKursu });
                }
            }

            return new JsonResult { Data = kursy, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        [AllowAnonymous]
        public JsonResult GetOpisKursu(Kurs item)
        {
            KursyDB db = new KursyDB();
            string opis = "";
            opis = db.Kursy.FirstOrDefault(x => x.IdKursu == item.IdKursu).Opis;
            return new JsonResult { Data = opis };
        }
        [AllowAnonymous]
        public JsonResult getKategoriaKursu(Kurs item)
        {
            KursyDB db = new KursyDB();
            Kategoria kategoria = new Kategoria();
            db.Kursy.Include(nameof(kategoria));
            var kurs = db.Kursy.FirstOrDefault(x => x.IdKursu == item.IdKursu);

            //categories.Add(new Kategoria() { Nazwa = "kat1", IdKategorii = 1 });
            //categories.Add(new Kategoria() { Nazwa = "kat2", IdKategorii = 2 });
            return new JsonResult { Data = new { status = true, kategoria = kurs.Kategoria.Nazwa, IdKategorii = kurs.Kategoria.IdKategorii } };
        }
        [AllowAnonymous]
        public JsonResult getKursy()

        {
            KursyDB db = new KursyDB();
            List<Kurs> kursy = new List<Kurs>();
            foreach (var dbkurs in db.Kursy)
            {
                if (dbkurs.Nazwa != "")
                {
                    kursy.Add(
                        new Kurs() { Nazwa = dbkurs.Nazwa, IdKursu = dbkurs.IdKursu });
                }
            }

            return new JsonResult { Data = kursy, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public JsonResult save(KursEdycjaSpotkaniaVM item)
        {
            Kategoria kategoriaKursu = new Kategoria();
            KursyDB db = new KursyDB();
            Kurs nowyKurs = new Kurs();
            EdycjaKursu nowaEdycjaKursu = new EdycjaKursu();
            List<Spotkanie> noweSpotkania = new List<Spotkanie>();
            kategoriaKursu.IdKategorii = item.IdKategoriiKursu;
            if (kategoriaKursu.IdKategorii == 0)
            {
                if (db.Kategorie.FirstOrDefault(x => x.Nazwa.Equals(item.NazwaKategorii)) != null)
                {
                    return new JsonResult { Data = new { status = false, wiadomosc = "Podana kategoria już istnieje, wybierz ją z listy" } };
                }
                kategoriaKursu = new Kategoria() { Nazwa = item.NazwaKategorii };
                try
                {
                    db.Kategorie.Add(kategoriaKursu);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                    return new JsonResult { Data = new { status = false, wiadomosc = "Nie udało się dodać kategorii, kursu, edycji, a także spotkań." } };
                }

            }
            if (item.IdKursu == 0)
            {
                if (db.Kursy.FirstOrDefault(x => x.Nazwa.Equals(item.NazwaKursu)) != null)
                {
                    return new JsonResult { Data = new { status = false, wiadomosc = "Podana nazwa kursu już istnieje, wybierz ją z listy" } };
                }
                nowyKurs.Nazwa = item.NazwaKursu;
                nowyKurs.Opis = item.Opis;
                nowyKurs.idKategorii = kategoriaKursu.IdKategorii;
                try
                {
                    db.Kursy.Add(nowyKurs);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    return new JsonResult { Data = new { status = false, wiadomosc = "Nie udało się dodać kursu, edycji, a także spotkań." } };
                }
                nowaEdycjaKursu.idKursu = nowyKurs.IdKursu;
            }
            else
            {
                nowaEdycjaKursu.idKursu = item.IdKursu;
            }

            nowaEdycjaKursu.NazwaEdycji = item.NazwaEdycji;
            nowaEdycjaKursu.WarunekUczestnictwa = item.Warunek;

            try
            {
                db.EdycjeKursu.Add(nowaEdycjaKursu);
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                return new JsonResult { Data = new { status = false, wiadomosc = "Nie udało się dodać edycji ani spotkań." } };
            }

            if (item.Lista == null)
            {
                return new JsonResult { Data = new { status = true, wiadomosc = "Dodano nowy kurs oraz edycję. W przyszłości uzupełnij spotkania." } };
            }
            try
            {
                foreach (Spotkanie spotkanie in item.Lista)
                {
                    db.Spotkania.Add(new Spotkanie()
                    {
                        TerminSpotkania = spotkanie.TerminSpotkania,
                        MiejsceSpotkania = spotkanie.MiejsceSpotkania,
                        idEdycji = nowaEdycjaKursu.IdEdycji
                    });

                }
                db.SaveChanges();
                return new JsonResult { Data = new { status = true, wiadomosc = "Pomyślnie zpaisano wszystkie dane." } };
            }
            catch (Exception ex)
            {
                return new JsonResult { Data = new { status = false, wiadomosc = "Nie udało się dodać spotkań." } };
            }

        }
    }

    public class KursEdycjaSpotkaniaVM
    {
        public string NazwaKursu { get; set; }

ObslugaKursow/ObslugaKursow/Views/EdycjaKursu/Contribute.cshtml
@using Microsoft.AspNet.Identity
@model ObslugaKursow.Models.EdycjaKursu



@using (Html.BeginForm("Uczestnicz", "Test", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    string UserID = User.Identity.GetUserId();
    <h3>Tekst</h3>
    @Html.HiddenFor(m => m.IdEdycji)
    <input multiple type="file" name="files" , value="Browse" />
    <br />
    <input type="submit" value="Dołącz" class="btn btn-primary " />

}

@if (ViewBag.UploadSuccess == true)
{
    <span>Pomyślnie dodano pliki</span>
}

ObslugaKursow/ObslugaKursow/Views/EdycjaKursu/Create.cshtml
@model ObslugaKursow.Models.EdycjaKursu

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


Do zrobienia dodawanie Kursu i spotkań w formie Master - Detail tak jak <a href="http://abctutorial.com/Post/35/mvc-5-master-details-using-jquery-ajax">tutaj</a>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $(document).ready(function () {
        $("#btnSubmit").click(function () {


            var mydata = $("#myForm").serialize();

            debugger
            $.ajax({
                type: "POST",
                url: "/EdycjaKursu/NowaKategoria",
                data: mydata,
                succes: function () {
                    alert("wgrane");
                }

            })
        })
    })
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ObslugaKursow/ObslugaKursow/Views/EdycjaKursu/Delete.cshtml
@model ObslugaKursow.Models.EdycjaKursu

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

ObslugaKursow/ObslugaKursow/Views/EdycjaKursu/Details.cshtml
@model ObslugaKursow.Models.EdycjaKursu

@{
    ViewBag.Title = "Details";
}

<h2>Szczegóły kursu:</h2>
<h4>@Model.Kurs.Nazwa, @Model.NazwaEdycji</h4>
@if (Model.Spotkania.Count != 0)
{
    <h5>
        @Model.Kurs.Opis
    </h5>

    <table class="table table-striped" , sortable="True">
        <tr>
            <th>
                Miejsce spotkania:
            </th>
            <th>
                Data spotkania
            </th>

        </tr>

        @foreach (var item in Model.Spotkania)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MiejsceSpotkania)
                </td>
                <td>
                    @Html.Label(item.TerminSpotkania.ToLongDateString()), godz. @item.TerminSpotkania.ToShortTimeString()
                </td>

            </tr>
        }
        <tr>
            <td align="left">
                @Html.ActionLink("Wróć do listy dostępnych kursów", "Index", null, new { @class = "btn btn-primary" })

            </td>
            <td align="right">
                @Html.ActionLink("Dołącz", "Contribute", new { id = Model.IdEdycji }, new { @class = "btn btn-primary" })

            </td>
        </tr>



    </table>
}
else
{
    <h4>Niestety, nie ustalono jeszcze terminów spotkań dla wybranego kursu, prosimy o cierpliwość.</h4>
    <table>       
    
        <tr>
            <td align="left">
                @Html.ActionLink("Wróć do listy dostępnych kursów", "Index", null, new { @class = "btn btn-primary" })

            </td>
            <td align="right">
            </td>
        </tr>
    </table>
}

ObslugaKursow/ObslugaKursow/Views/EdycjaKursu/Edit.cshtml
@model ObslugaKursow.Models.EdycjaKursu

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

ObslugaKursow/ObslugaKursow/Views/EdycjaKursu/Index.cshtml
@model IEnumerable<ObslugaKursow.Models.EdycjaKursu>



<h2>Lista dostępnych kursów</h2>


<table class="table table-striped">
    <tr>
        <th>
            Nazwa Kursu
        </th>
        <th>
            Warunek Uczestnictwa
        </th>
        <th>
            Nazwa Edycji
        </th>
        <th>
            Pierwsze spotkanie
        </th>
        <th>

        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Kurs.Nazwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WarunekUczestnictwa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NazwaEdycji)
            </td>
            <td>
                @{
                    string nazwa = "";
                    if (item.Spotkania.OrderBy(x => x.TerminSpotkania).FirstOrDefault() != null)
                    {
                        nazwa = item.Spotkania.OrderBy(x => x.TerminSpotkania).FirstOrDefault().TerminSpotkania.ToShortDateString();
                    }
                    else
                    {
                        nazwa = "Brak informacji";
                    }
                    <div>@nazwa</div>
                }

            </td>
            <td>
                @Html.ActionLink("Poznaj Szczegóły", "Details", new { id = item.IdEdycji }, new { @class = "btn btn-primary " }) 
                @Html.ActionLink("Dołącz", "Contribute", new { idEdycji = item.IdEdycji }, new { @class = "btn btn-primary" })
            </td>
        </tr>
    }

</table>